/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class GUI extends javax.swing.JFrame {    
    /**
     * Creates new form GUI
     */
    private void kosongkan_form(){
        txtNOREG.setEditable(true);
        txtNOREG.setText(null);
        txtMERK.setText(null);
        txtTYPE.setText(null);
        txtTAHUN.setText(null);
        txtWARNA.setText(null);
     }
     
    private void tampilkan_data(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("NOMOR REGISTRASI");
        model.addColumn("MERK");
        model.addColumn("TYPE");
        model.addColumn("TAHUN");
        model.addColumn("WARNA");
        model.addColumn("GRADE KENDARAAN");
        
        try{
            int no = 1;
            String sql = "select* from listkendaraan";
            java.sql.Connection conn=(Connection)koneksi.configDB();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                model.addRow (new Object[]{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
            }
            tabellistkendaraan.setModel(model);
        }catch(SQLException e){
            System.out.println("Error :"+e.getMessage());
        }
    }
    
    public GUI(){
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMERK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTYPE = new javax.swing.JTextField();
        txtWARNA = new javax.swing.JTextField();
        btSIMPAN = new javax.swing.JButton();
        btEDIT = new javax.swing.JButton();
        btHAPUS = new javax.swing.JButton();
        btRESET = new javax.swing.JButton();
        btKELUAR = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        statuskoneksi = new javax.swing.JLabel();
        txtTAHUN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNOREG = new javax.swing.JTextField();
        cbGRADE = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabellistkendaraan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("DATA KENDARAAN SUMBER JAYA SHOWROOM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 14));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("MERK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(txtMERK, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 90, -1));

        jLabel4.setText("TYPE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setText("TAHUN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setText("WARNA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(txtTYPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, -1));
        jPanel1.add(txtWARNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, -1));

        btSIMPAN.setText("Simpan");
        btSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSIMPANActionPerformed(evt);
            }
        });
        jPanel1.add(btSIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, -1));

        btEDIT.setText("Edit");
        btEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEDITActionPerformed(evt);
            }
        });
        jPanel1.add(btEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 63, -1));

        btHAPUS.setText("Hapus");
        btHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHAPUSActionPerformed(evt);
            }
        });
        jPanel1.add(btHAPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, -1));

        btRESET.setText("Reset");
        btRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRESETActionPerformed(evt);
            }
        });
        jPanel1.add(btRESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 90, -1));

        btKELUAR.setText("Keluar");
        btKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKELUARActionPerformed(evt);
            }
        });
        jPanel1.add(btKELUAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel11.setText("Status Koneksi");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 424, -1, -1));

        statuskoneksi.setText(":");
        jPanel1.add(statuskoneksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 424, -1, -1));
        jPanel1.add(txtTAHUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, -1));

        jLabel7.setText("GRADE KENDARAAN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, -1, 20));

        jLabel2.setText("NOMOR REGISTRASI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtNOREG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOREGActionPerformed(evt);
            }
        });
        jPanel1.add(txtNOREG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, -1));

        cbGRADE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Grade", "S", "A", "B", "C" }));
        jPanel1.add(cbGRADE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 450));

        tabellistkendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabellistkendaraan.getTableHeader().setReorderingAllowed(false);
        tabellistkendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellistkendaraanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabellistkendaraan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 520, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKELUARActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btKELUARActionPerformed

    private void btHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHAPUSActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from listkendaraan where noreg='"+txtNOREG.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Berhasil dihapus");
            
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_btHAPUSActionPerformed

    private void btSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSIMPANActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "insert into listkendaraan values ('"+txtNOREG.getText()+"','"+txtMERK.getText()+"','"+txtTYPE.getText()+"','"+Integer.parseInt(txtTAHUN.getText())+"','"+txtWARNA.getText()+"','"+cbGRADE.getSelectedItem()+"')";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();    
    }//GEN-LAST:event_btSIMPANActionPerformed

    private void tabellistkendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellistkendaraanMouseClicked
        // TODO add your handling code here:
        int baris = tabellistkendaraan.rowAtPoint(evt.getPoint());
        String noreg = tabellistkendaraan.getValueAt(baris, 1).toString();
        txtNOREG.setText(noreg);
        
        String merk= tabellistkendaraan.getValueAt(baris, 2).toString();
        txtMERK.setText(merk);
        
        String type= tabellistkendaraan.getValueAt(baris, 3).toString();
        txtTYPE.setText(type);
        
        String tahun= tabellistkendaraan.getValueAt(baris, 4).toString();
        txtTAHUN.setText(tahun);
        
        String warna= tabellistkendaraan.getValueAt(baris,5).toString();
        txtWARNA.setText(warna);
        
        String gradekendaraan = tabellistkendaraan.getValueAt(baris, 6).toString();
        cbGRADE.setSelectedItem(gradekendaraan);
    }//GEN-LAST:event_tabellistkendaraanMouseClicked

    private void btRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRESETActionPerformed
        // TODO add your handling code here:
        kosongkan_form();
    }//GEN-LAST:event_btRESETActionPerformed

    private void txtNOREGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOREGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOREGActionPerformed

    private void btEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEDITActionPerformed
        // TODO add your handling code here:
        try{
            String sql= "update listkendaraan set noreg ='"+txtNOREG.getText()+"',merk ='"+txtMERK.getText()+"',type = '"+txtTYPE.getText()+"',tahun ='"+Integer.parseInt(txtTAHUN.getText())+"',warna ='"+txtWARNA.getText()+"',gradekendaraan ='"+cbGRADE.getSelectedItem()+"' where noreg = '"+txtNOREG.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Mengedit data");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_btEDITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEDIT;
    private javax.swing.JButton btHAPUS;
    private javax.swing.JButton btKELUAR;
    private javax.swing.JButton btRESET;
    private javax.swing.JButton btSIMPAN;
    private javax.swing.JComboBox cbGRADE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel statuskoneksi;
    private javax.swing.JTable tabellistkendaraan;
    private javax.swing.JTextField txtMERK;
    private javax.swing.JTextField txtNOREG;
    private javax.swing.JTextField txtTAHUN;
    private javax.swing.JTextField txtTYPE;
    private javax.swing.JTextField txtWARNA;
    // End of variables declaration//GEN-END:variables
}
